-- LOCATION-SERVICE
CREATE DATABASE location_db;
CREATE DATABASE user_db;
CREATE DATABASE vehicle_db;
CREATE DATABASE driver_db;
CREATE DATABASE trip_db;
CREATE DATABASE notification_db;
CREATE DATABASE payment_db;
