# ===============================
# APP
# ===============================
spring.application.name=location-service
server.port=5000
# ===============================
# REDIS
# ===============================
spring.data.redis.host=redis-server
spring.data.redis.port=6379
spring.data.redis.timeout=2000
# Lettuce connection pool
spring.data.redis.lettuce.pool.max-active=5
spring.data.redis.lettuce.pool.max-idle=3
spring.data.redis.lettuce.pool.min-idle=1
# ===============================
# POSTGRESQL
# ===============================
spring.datasource.url=${DB_URL:jdbc:postgresql://postgres-db:5432/location_db}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
# HikariCP
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=2000
spring.datasource.hikari.max-lifetime=1800000
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# ===============================
# SERVER THREAD
# ===============================
server.tomcat.threads.max=50
server.tomcat.threads.min-spare=10
# ===============================
# WORKER CONFIG
# ===============================
app.buffer.max-size=500
app.buffer.flush-interval=5000
app.worker.time-out=3000000000
app.worker.cleanup-interval=5000
# ===============================
# LOGGING
# ===============================
logging.level.org.springframework.jdbc.core=INFO
logging.level.org.springframework.data.redis=INFO
# ===============================
# KAFKA
# ===============================
spring.kafka.bootstrap-servers=kafka-server:29092
# Consumer
spring.kafka.consumer.group-id=location-service
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.enable-auto-commit=false
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer-class-config=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JacksonJsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.value.default.type=com.mywebsite.locationservice.model.event.DriverAcceptedEvent
spring.kafka.listener.ack-mode=record
spring.kafka.listener.concurrency=2
