spring.application.name=booking-service
server.port=5000

spring.datasource.url=jdbc:postgresql://db:5432/booking_db
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:kafka-server:29092}
spring.kafka.consumer.group-id=booking-service-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

app.outbox.polling-rate=${OUTBOX_POLLING_RATE:5000}

service.user.url=${USER_SERVICE_URL:http://user-service:5000}
service.vehicle.url=${VEHICLE_SERVICE_URL:http://vehicle-service:5000}
service.driver.url=${DRIVER_SERVICE_URL:http://driver-service:5000}
service.location.url=${LOCATION_SERVICE_URL:http://location-service:5000}
service.notification.url=${NOTIFICATION_SERVICE_URL:http://notification-service:5000}

